### ISSUE TITLE
stopping server show's this

### ISSUE THREAD

**Issue by HQPusHErx15** [WINGS07/JDLogger_releases#1]
just look into it and please fix it :x

using paper-169

[bug.txt](https://github.com/WINGS07/JDLogger_releases/files/7919109/bug.txt)

**Comment by WINGS07** [comment]
Hello, is it windows OS?

**Comment by WINGS07** [comment]
Closed in version 8.0, but not tested. Please check this version and write if you have any problems.

Note: Auto update and other update features not working on Windows OS.

**Comment by WINGS07** [comment]
_P.S, now Windows Auto Update working, install latest version again_
